(load "./test-manager/load.scm")

(define (triangle row column)
  (define (at-edge? row column)
    (or (= column 1)
	(= row column)))
  (define (higher-row row)
    (- row 1))
  (define (column-to-left column)
    (- column 1))
  (define (column-to-right column)
    column)
  (define (iterate row column)
    (if (at-edge? row column)
	1
	(+ (triangle (higher-row row) (column-to-left column))
	   (triangle (higher-row row) (column-to-right column)))))
  (iterate row column))

(define-test (triangle)
  (assert-= (triangle 1 1)
	    1)
  (assert-= (triangle 2 1)
	    1)
  (assert-= (triangle 2 2)
	    1)
  (assert-= (triangle 3 1)
	    1)
  (assert-= (triangle 3 2)
	    2)
  (assert-= (triangle 3 3)
	    1)
  (assert-= (triangle 4 1)
	    1)
  (assert-= (triangle 4 2)
	    3)
  (assert-= (triangle 4 3)
	    3)
  (assert-= (triangle 4 4)
	    1)
  (assert-= (triangle 5 1)
	    1)
  (assert-= (triangle 5 2)
	    4)
  (assert-= (triangle 5 3)
	    6)
  (assert-= (triangle 5 4)
	    4)
  (assert-= (triangle 5 5)
	    1))

(run-registered-tests)

